### ISSUE TITLE
Consider changing name of this repo

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.pkgdown.rmitemplate#15]
Directories that end with `.template` are interpreted as a file extension on Mac, with the Pages template file type. 

This is a bit of a pain, and may be worth nipping in the bud.

**Comment by AlexAxthelm** [comment]
`pacta.template.pkgdown`?

**Comment by cjyetman** [comment]
Originally I modeled this after https://github.com/tidyverse/tidytemplate/ and https://github.com/ropensci-org/rotemplate. Either I added the "." to stick with our pacta repos naming scheme, or they changed those names later. I think `pacta.pkgdowntemplate` might be logical?

**Comment by jdhoffa** [comment]
Since this repo is actively used in workflows to generate several pkgdown websites, may I suggest the following next steps:

- [ ] Archive (not delete) this repo
- [ ] Fork repo with new name suggested by @cjyetman 
- [ ] Open PRs to all relevant repos pointing to new template repo
- [ ] Transfer issues

I think all the relevant people are already on this thread, do you both agree with that strategy?

**Comment by cjyetman** [comment]
I think you can just rename this repo and then open the PRs in the other repos to point to the new name, no?

**Comment by jdhoffa** [comment]
Either works. 

- The fork strategy means there's no downtime (or, if we somehow miss updating a repo to point to it, the repo will still generate a website based on the old template)
- The simpler strategy means we may break things

**Comment by cjyetman** [comment]
ah, now I get why you suggested that... up to you

**Comment by AlexAxthelm** [comment]
I vote for rename. Unless we open a new repo with the old name, everything _should_ work as normal:

> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by jdhoffa** [comment]
I followed the `tidytemplate` style for the repository name.

I will leave this issue open for now until all repositories that use this workflow have updated their `pkgdown` workflows.

**Comment by jdhoffa** [comment]
AFAIK @cjyetman and myself are the only ones that make use of this `pkgdown` template but just in case:
FYI @RMI-PACTA/developers

**Comment by AlexAxthelm** [comment]
See current status of migrating to new name: https://github.com/search?q=org%3ARMI-PACTA%20rmi-pacta%2Fpacta.pkgdown.template&type=code

**Comment by cjyetman** [comment]
hmmmm.... I thought we would also have to update our DESCRIPTION files, but I'm getting errors on my PRs
> Caused by error: 
>  ! Could not solve package dependencies:
>  * deps::.: Can't install dependency rmi-pacta/pacta.pkgdown.rmitemplate
>  * local::.: Can't install dependency rmi-pacta/pacta.pkgdown.rmitemplate

**Comment by jdhoffa** [comment]
I'll look into it. Guess this morning is a `pkgdown` morning :D

**Comment by cjyetman** [comment]
maybe GitHub just needs some time to properly propagate the new name

**Comment by jdhoffa** [comment]
Yeah let's give it a little bit, and if we're still having trouble this afternoon we can look into it?

**Comment by cjyetman** [comment]
"break now, fix later" 🤣

**Comment by jdhoffa** [comment]
> "break now, fix later" 🤣


I mean, I opted for the safer approach!

You both voted for the faster one 😂

**Comment by jdhoffa** [comment]
> See current status of migrating to new name: https://github.com/search?q=org%3ARMI-PACTA%20rmi-pacta%2Fpacta.pkgdown.template&type=code

Want to nip this in the bud before we forget. Based on the search above, we have:

Open PRs related to this:

- [ ]  https://github.com/RMI-PACTA/pacta.interactive.plot/pull/42
- [ ] https://github.com/RMI-PACTA/pactaverse/pull/24
- [ ] https://github.com/RMI-PACTA/pacta.data.preparation/pull/326
- [ ] https://github.com/RMI-PACTA/pacta.data.scraping/pull/33
- [ ] https://github.com/RMI-PACTA/pacta.executive.summary/pull/286

Not relevant because archived:
https://github.com/RMI-PACTA/pacta.portfolio.analysis
https://github.com/RMI-PACTA/pacta.interactive.report

**Comment by jdhoffa** [comment]
Done!
Closing this comment
