### ISSUE TITLE
add a link to PACTA's sub-site on rmi.org

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.pkgdown.rmitemplate#29]
not sure where, but it would be nice to integrate https://pacta.rmi.org into the template somewhere

**Comment by jdhoffa** [comment]
Maybe as a link on one of the logos? 
![Screenshot 2024-03-07 at 09 57 21](https://github.com/RMI-PACTA/pacta.pkgdown.rmitemplate/assets/8741309/f3c8053f-519f-4254-8097-75b5093c0066)

**Comment by jdhoffa** [comment]
Yeah, it's just tricky from a UI perspective since we don't have a nice looking icon for PACTA (and I have no intention of designing one XD)

**Comment by cjyetman** [comment]
maybe the link icon `<i class="fa-solid fa-link"></I>`?
🔗

**Comment by jdhoffa** [comment]
I've just asked if we have a `.svg` of the PACTA logo somewhere :-)
