### ISSUE TITLE
See if logo is also necessary in footer

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.pkgdown.rmitemplate#4]
This also seems a bit crammed and has somewhat awkward spacing: 

<img width="1351" alt="Screen Shot 2022-11-29 at 4 11 43 PM" src="https://user-images.githubusercontent.com/8741309/204566886-70be3312-82a3-4fb9-819e-d32e7a809a03.png">

Most other tidy-templates seem to have a much more simple footer: 

<img width="1205" alt="Screen Shot 2022-11-29 at 4 13 03 PM" src="https://user-images.githubusercontent.com/8741309/204567209-163b97d4-4d2f-48dc-9be6-2d2ff1cff265.png">

**Comment by cjyetman** [comment]
FYI... I was working towards trying to achieve something that mirrors RMI's own webpages, like https://rmi.org/our-work/climate-finance/

obviously, there's still a lot of work to be done to achieve that LOL

**Comment by jdhoffa** [comment]
Ah understood. Maybe this is something we should coordinate with RMI comms then? I would almost tend to prefer we keep them somewhat distinct from RMI logo/ design (to indicate that it is related but not necessarily approved content), does that make sense? Otherwise we will definitely need to have all of these sites go through a full approval cycle with comms and I'm not sure we're ready for that...

**Comment by cjyetman** [comment]
I'd love that, but I don't know if we can get them to pay that much attention to us. LOL

**Comment by jdhoffa** [comment]
So the responsibility is actually on us, not them I think... We are supposed to ensure that comms signs off on our public-facing stuff. 

That's what I'm getting at lol, I can't be arsed to do that, so would rather remove the logo and not risk getting told off

**Comment by cjyetman** [comment]
ah, I thought you meant Comms might help determine what is the best design given their corporate branding, which to me would be ideal

**Comment by jdhoffa** [comment]
Yeah that might be the case as well. Would coordinate that with @AlexAxthelm probably

**Comment by jdhoffa** [comment]
Superseded by #25
